### ISSUE TITLE
Usage to solver the captcha

### ISSUE THREAD

**Issue by robertveloso** [dsaveliev/CaptchaSolver#3]
I'm already unpack the files, ran the script but only get to Optimization Finished. How should I solver the captcha would it be: python all_digits.py captcha.jpg?

**Comment by robertveloso** [comment]
How did you generate this dataset?

**Comment by dsaveliev** [comment]
Dataset was collected from [this site](http://services.fms.gov.ru/info-service.htm?sid=2000) and marked by hands.
You just need to unpack both archives in the working directory and run the scripts.
